version: '3.8'

x-php-config:
  &php-config
  env_file:
    - .env
  build:
    context: ../backend
    args:
      user: www
      uid: 80
  restart: unless-stopped

services:

  backend:
    <<: *php-config
    depends_on:
      - pgsql

  frontend:
    build:
      context: ../frontend
    restart: unless-stopped

  scheduler:
    <<: *php-config
    command: bash -c "while true; do php artisan donations:load-from-donate-pay; sleep 16; done"
    depends_on:
      - backend

  pgsql:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
